apiVersion: apps/v1
kind: Deployment
metadata:
  name: kimup-operator
  namespace: kimup-operator
  labels:
    app.kubernetes.io/name: kube-image-updater
    app.kubernetes.io/instance: kimup-operator
    app.kubernetes.io/component: controller
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-image-updater
      app.kubernetes.io/instance: kimup-operator
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-image-updater
        app.kubernetes.io/instance: kimup-operator
        app.kubernetes.io/component: controller
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: kimup
      securityContext:
        runAsNonRoot: true
      containers:
        - name: operator
          image: "ghcr.io/orange-cloudavenue/kimup-operator:latest"
          imagePullPolicy: IfNotPresent
          args:
            - --healthz
            - --metrics
            - --leader-elect
          ports:
            - containerPort: 8443
              name: webhook-server
              protocol: TCP
            - containerPort: 9080
              name: metrics
              protocol: TCP
            - containerPort: 9081
              name: healthz
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - "ALL"
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: webhook-cert
              readOnly: true
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          readinessProbe:
              httpGet:
                path: /readyz
                port: 9081
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9081
      volumes:
      - name: webhook-cert
        secret:
          defaultMode: 420
          secretName: kimup-webhook-serving-cert
