apiVersion: apps/v1
kind: Deployment
metadata:
  name: kimup-operator
  namespace: kimup-operator
  labels:
    app.kubernetes.io/name: kube-image-updater
    app.kubernetes.io/instance: kimup-operator
    app.kubernetes.io/component: controller
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-image-updater
      app.kubernetes.io/instance: kimup-operator
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-image-updater
        app.kubernetes.io/instance: kimup-operator
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: kimup
      containers:
        - name: operator
          image: "ghcr.io/orange-cloudavenue/kimup-operator:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
              name: webhook-server
              protocol: TCP
            - containerPort: 8080
              name: metrics
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: webhook-cert
              readOnly: true
          # readinessProbe:
          #     httpGet:
          #       path: /readyz
          #       port: 8081
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 8081
          # resources:

      volumes:
      - name: webhook-cert
        secret:
          defaultMode: 420
          secretName: kimup-webhook-serving-cert
