apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - role.yaml
  - role_binding.yaml
  - service_account.yaml
  - webhook-certificate.yaml
  - deployment.yaml
  - service.yaml