apiVersion: v1
kind: Service
metadata:
  name: mutator
  namespace: kimup-operator
  labels:
    app.kubernetes.io/name: kube-image-updater
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    app.kubernetes.io/name: kube-image-updater
    app.kubernetes.io/instance: kimup-operator