apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: kimup-operator
    app.kubernetes.io/name: kube-image-updater
  name: kimup-operator
  namespace: kimup-operator
spec:
  containers:
    - image: kurun://cmd/operator/main.go
      name: operator
      args:
        - "/main"
        - "--metrics"
        - "--metrics-port=9080"
        - "--healthz"
        - "--healthz-port=9081"
        - "--leader-elect"
      ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 9080
          name: metrics
          protocol: TCP
        - containerPort: 9081
          name: healthz
          protocol: TCP
      volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: webhook-cert
          readOnly: true
      readinessProbe:
          httpGet:
            path: /readyz
            port: 9081
      livenessProbe:
        httpGet:
          path: /healthz
          port: 9081
  serviceAccount: kimup
  serviceAccountName: kimup
  volumes:
  - name: webhook-cert
    secret:
      defaultMode: 420
      secretName: kimup-webhook-serving-cert