apiVersion: v1
kind: Namespace
metadata:
  name: dev-kube-image-updater
  annotations:
    kimup.cloudavenue.io/enabled: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: dev-kube-image-updater
  labels:
    app.kubernetes.io/name: whoami
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: whoami
  template:
    metadata:
      # annotations:
      #   kimup.cloudavenue.io/enabled: "false"
      labels:
        app.kubernetes.io/name: whoami
    spec:
      containers:
        - name: whoami
          image: "traefik/whoami:latest"
          imagePullPolicy: IfNotPresent

---
apiVersion: kimup.cloudavenue.io/v1alpha1
kind: Image
metadata:
  labels:
    app.kubernetes.io/name: whoami
  name: traefik-whoami
  namespace: dev-kube-image-updater
spec:
  image: traefik/whoami
  baseTag: v1.10.0
  triggers:
    - type: crontab
      value: "00 00 */12 * * *"
  rules:
    - name: Automatic update semver patch
      type: semver-patch
      actions:
        - type: apply
