# permissions for end users to view images.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-image-updater
    app.kubernetes.io/managed-by: kustomize
  name: image-viewer-role
rules:
- apiGroups:
  - kimup.cloudavenue.io
  resources:
  - images
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kimup.cloudavenue.io
  resources:
  - images/status
  verbs:
  - get
