apiVersion: apps/v1
kind: Deployment
metadata:
  name: golink
  namespace: default
  labels:
    app: golink
spec:
  selector:
    matchLabels:
      app: golink
  replicas: 1
  template:
    metadata:
      annotations:
        kimup.cloudavenue.io/enabled: "true"
      labels:
        app: golink
    spec:
      containers:
      - name: golink
        image: ghcr.io/azrod/golink:latest
        # command: ["/bin/sh"]
        # args: ["-c", "apt-get update; apt install -y wget systemctl vim net-tools curl; wget https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.101.0/otelcol-contrib_0.101.0_linux_arm64.deb ; mkdir -p /var/lib/otelcol/file_storage/output /var/lib/otelcol/file_storage/receiver ; chmod 777 /var/lib/otelcol/file_storage/output /var/lib/otelcol/file_storage/receiver ; dpkg -i --force-confold otelcol-contrib_0.101.0_linux_arm64.deb ; sleep 604800"]
        imagePullPolicy: IfNotPresent
        # ports:
        #   - containerPort: 9091
        #   - containerPort: 8888
        #   - containerPort: 4242