---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
  namespace: default
webhooks:
  - sideEffects: None 
    admissionReviewVersions: ["v1"]
    name: your.example.com
    clientConfig:
      url: https://your.example.com:8443/mutate
      # service:
      #   name: kimup-webhook-mutating
      #   namespace: default
      #   path: /mutate
      #   port: 8443
      # CA certificate with BEGIN and END lines - base64 encoded
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZFekNDQXZ1Z0F3SUJBZ0lDQitZd0RRWUpLb1pJaHZjTkFRRUxCUUF3R3pFWk1CY0dBMVVFQ2hNUWVXOTEKY2k1bGVHRnRjR3hsTG1OdmJUQWVGdzB5TkRBNU1qY3dPRFUxTXpoYUZ3MHlOVEE1TWpjd09EVTFNemhhTUJzeApHVEFYQmdOVkJBb1RFSGx2ZFhJdVpYaGhiWEJzWlM1amIyMHdnZ0lpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElDCkR3QXdnZ0lLQW9JQ0FRRE9tZmpIcGp4VXlxc1lkZHZzckVneEliNkVNMlh4eDBHK3lML0I0dURDU1dnNE10MU0KK1hSU0tSZnROeGxBZGIvWGlUZXo2N1ZsVGtxV1pzZTIrWW9sOEFqckRpSzJvY1dLSk15NitzS291T1ZVS2JkdgpJdElyb2VBNHpFMHJTYnViZDVXTTFKcEZPczRYMHN1NWhMWFZSYnR4VS9kcENGb2xDdWEwMWNGc0J5bXBNS283CmZEUXpERE5wVDZsditOUDh5NHYraGc0ZGN2aE43MlREQW9yWWVkN1lCK2w0R0hxK2JBQ2t0UFNLcnVmWXZ3OFAKR3lWU0NpZVFWb0VHVGIxZkJvMW1LUWpMVUhCNk9DckFGTHVEeWxMd2hHbmFOWEZxT0pBVFR6RGVkTkxmQU15MQpSVTgydktzK1ZPRTRuSnFIeU5McjBlSkw1bGtZdllheFFTRXN6dTVwY1RPZk1Zc0Z2THBEbmNteUF5TGRsSUdYCkc4TjFTbTlmUlc1dEFlbFBnMFZNcmlXWFZCMzVOeFJWcDBrTjF6d1B5elNDSmxCb2FMa21KQmsxUmdFRTdCNkYKSkRWQWFZRFMvMVVQMTJBcVdBeHlEU0M1SGd2M05pTGhCUmpmYXZxc1AySmNYRExvTElGWE1YZXNtRXhCa3JQNwozUVVDMmtmV1NDcFB0WlJ5dW12Y1g4NGVKcXJob0JTOTFUWTRadXlQNmZhSGdsRTJhSXErb243cDVEeEtFb28rCjdkQ3ZlVk9WdzlnNUxuMUw3T1dCNUY2Wko1Y3JtbVJvcGFaNHlBbmtHQnZ1azdUTjdob0V2SjhCMzMvcUtiZ0wKQ2lvM2FCN3J6SjB2aUdUeERyd1BzUUxIWDEvNzRGeHBvRUhDVzg0Vm9Rdms0TWZTTVJMVCtyZHVtd0lEQVFBQgpvMkV3WHpBT0JnTlZIUThCQWY4RUJBTUNBb1F3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdJR0NDc0dBUVVGCkJ3TUJNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGS0lrUWtjZUYzMExVdXJyN3Zoc1VKT24KOUZnNE1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQTREVUZUeEVyTEZ3ZWZTcGdXR241WHFjbVhsekVWUE5oNgpuWFJxYWoyTGN5SUZTazJtejBEWnMwMGRZTUFJZG9KYXB2VW0vUVRXMFMyeTc5ekpCbmd1a3hoV1RFV3ZDMWpCCnlTSnNjMFVtTmk5YUJXellPVHU5VXlOZjdkb2ZoSFVFd0o4Mlo3Q1R3ajBnb2doMGxJdjFOeTl4ZzJqb0xUU0cKUmpxOEJZOXBBek1SRXgvRTh3dGhnMHRPTlprM3lXN3k2S3dVQ0dFU0d1MEoyWlU1VThobDQ3TUVNVmRpWjZjTQoxRmNZZXFlMmwzYnkvNVpVYVh4N0xieXhrZHdPbGw1K1VOL2Y5Z2d3OSt3RTJybFA0NzQrb2p2QWtPV1loSWVpCkNDU0NQNnZhMkNEdFJLOVl1bWlUbTQrb0QvNXQ5U3Y5dXVaamhaMmsyODV0MHV5ZGZKOEZnWmsreUxsTjhmK1oKdmo2TDZBbWVFTXByNTdiQlNKMlJXaU1wVGJFeVAyTkloRkVmeWUvN0djdUZmUEhZSDJ2V2dIRUdyUHBzZWNIdQpWbUhmVW1DTDZ1L2c0ZGdzaFFJME5iOTI1NlBPdndFMVB3aFNLbnh2YWh6QkN1ZG9zUksyQXVvbG5XNU91YXlOCmtRUXBlY3hsNTJkQ1lWc1BBN1pQdFNyRXdJdUdxTWNFd1p1dGNmMmJaalRMVjN2S3lwZmV5cTViWUF3V1E4V2MKbEw0OWV3aE1qSVM1cWhSckY2bHNvRnJtc0xodm5iaUtJS1NKNzczZkVGQ09OU3hkMmdTb1VZd2tFdTdmSkhHRwpIQ1F6cHhzQ2NEM3gxQ2N3elEvTFF6ZURnL3lZbU55WC9BZ2FkUy9aZEZjQXpSTTRyUTRnQ0F5MW5OaTZUdXNlCjdHa281dlhBZnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    rules:
      - operations: [ "CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced" 
        # namespaceSelector:
        #   matchExpressions:
        #     - {key: "name", operator: "In", values: ["core-services"]}
    failurePolicy: Fail
    
 
