---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
  namespace: default
webhooks:
  - sideEffects: None
    admissionReviewVersions: ["v1"]
    name: kimup-webhook-mutating.default.svc
    clientConfig:
      # url: https://kimup-webhook-mutating.default.svc.cluster.local:8443/mutate
      service:
        name: kimup-webhook-mutating
        namespace: default
        path: /mutate
        port: 8443
      # CA certificate with BEGIN and END lines - base64 encoded
      # caBundle: "LS0tLS1CRUdJTiBDRVJUSU.."
    rules:
      - operations: [ "CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced" 
        # namespaceSelector:
        #   matchExpressions:
        #     - {key: "name", operator: "In", values: ["core-services"]}
    failurePolicy: Fail
    
 