name: 'Force pkg.go.dev release sync'

on:
    release:
        types: [published]

jobs:
    build:
        name: Renew documentation
        runs-on:
            group: Default
        steps:
            - name: Pull new module version
              uses: andrewslotin/go-proxy-pull-action@master
