name: 'Force update pkg.go.dev/doc.crds.dev release sync'

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  pkg-go-dev:
    name: Renew documentation
    runs-on:
        group: Default
    steps:
        - name: Pull new module version
          uses: andrewslotin/go-proxy-pull-action@master
  doc-crds-dev:
    name: Renew documentation
    runs-on:
        group: Default
    steps:
        - name: update doc.crds.dev
          uses: azrod/doc-crds-dev-update-action@master
